name: cards
description: "A minimal cards app with offline support."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.4
  path: ^1.9.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  min_sdk_android: 21
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon.png"
